export const time = {
    Millisecond: 1,
    Second: 1000,
    Minute: 60_000,
    Hour: 3_600_000,
} as const;

export const MimeTypes = {
    audio: {
        "audio/aac": [".aac"],
        "audio/mpeg": [".mp3"],
        "audio/wav": [".wav"],
        "audio/webm": [".webm"],
        "audio/flac": [".flac"],
        "audio/x-m4a": [".m4a"],
        "audio/ogg": [".oga", ".opus"],
        "audio/midi": [".mid", ".midi"],
        "audio/x-midi": [".mid", ".midi"],
        "audio/3gpp": [".3gp"],
        "audio/3gpp2": [".3g2"],
    },
    video: {
        "video/mp4": [".mp4"],
        "video/webm": [".webm"],
        "video/ogg": [".ogv"],
        "video/mpeg": [".mpeg"],
        "video/x-msvideo": [".avi"],
        "video/mp2t": [".ts"],
        "video/3gpp": [".3gp"],
        "video/3gpp2": [".3g2"],
    },
    image: {
        "image/jpeg": [".jpg", ".jpeg"],
        "image/png": [".png"],
        "image/webp": [".webp"],
        "image/apng": [".apng"],
        "image/avif": [".avif"],
        "image/bmp": [".bmp"],
        "image/gif": [".gif"],
        "image/vnd.microsoft.icon": [".ico"],
        "image/svg+xml": [".svg"],
        "image/tiff": [".tif", ".tiff"],
    },
    application: {
        "application/pdf": [".pdf"],
        "application/zip": [".zip"],
        "application/vnd.rar": [".rar"],
        "application/x-7z-compressed": [".7z"],
        "application/x-abiword": [".abw"],
        "application/x-freearc": [".arc"],
        "application/vnd.amazon.ebook": [".azw"],
        "application/octet-stream": [".bin"],
        "application/x-bzip": [".bz"],
        "application/x-bzip2": [".bz2"],
        "application/x-cdf": [".cda"],
        "application/x-csh": [".csh"],
        "application/msword": [".doc"],
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document":
            [".docx"],
        "application/vnd.ms-fontobject": [".eot"],
        "application/epub+zip": [".epub"],
        "application/gzip": [".gz"],
        "application/java-archive": [".jar"],
        "application/json": [".json"],
        "application/ld+json": [".jsonld"],
        "application/vnd.apple.installer+xml": [".mpkg"],
        "application/vnd.oasis.opendocument.presentation": [".odp"],
        "application/vnd.oasis.opendocument.spreadsheet": [".ods"],
        "application/vnd.oasis.opendocument.text": [".odt"],
        "application/ogg": [".ogx"],
        "application/x-httpd-php": [".php"],
        "application/vnd.ms-powerpoint": [".ppt"],
        "application/vnd.openxmlformats-officedocument.presentationml.presentation":
            [".pptx"],
        "application/rtf": [".rtf"],
        "application/x-sh": [".sh"],
        "application/x-tar": [".tar"],
        "application/vnd.visio": [".vsd"],
        "application/xhtml+xml": [".xhtml"],
        "application/vnd.ms-excel": [".xls"],
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": [
            ".xlsx",
        ],
        "application/xml": [".xml"],
        "application/vnd.mozilla.xul+xml": [".xul"],
    },
    text: {
        "text/plain": [".txt"],
        "text/markdown": [".md"],
        "text/css": [".css"],
        "text/csv": [".csv"],
        "text/html": [".htm", ".html"],
        "text/calendar": [".ics"],
        "text/javascript": [".js", ".mjs"],
    },
    font: {
        "font/otf": [".otf"],
        "font/ttf": [".ttf"],
        "font/woff": [".woff"],
        "font/woff2": [".woff2"],
    },
} as const;
